PREFIX dcx:<http://galyn.example.com/source_data_files/data_Complex.csv#>
PREFIX scx:<http://galyn.example.com/source_data_files/setup_Complex.csv#>
PREFIX ssx:<http://galyn.example.com/source_data_files/setup_Simplex.csv#>
PREFIX sxcxcx:<http://galyn.example.com/source_data_files/setup_xref_Complex-Complex.csv#>
PREFIX ix_ebd:<http://galyn.example.com/constructed_statements/index/events_by_date/#>

INSERT {
  GRAPH <http://galyn.example.com/constructed_statements/index/events_by_date/> {
    ?event ix_ebd:mindate ?mindate;
           ix_ebd:maxdate ?maxdate.
  }
}
WHERE {
  SELECT ?macro ?melabel ?event ?evlabel (MIN(?evdate) as ?mindate) (MAX(?evdate) as ?maxdate)
  WHERE {
    ?macro a scx:r1;
           dcx:Identifier ?melabel;
           sxcxcx:r61 ?event.
    ?event dcx:Identifier ?evlabel;
           sxcxcx:r62 ?_1.
    ?_1 sxcxcx:r64 ?_2.
    {
      ?_2 sxcxcx:r78 ?_3.
      ?_3 sxcxcx:r103 ?_4.
      ?_4 sxcxcx:r104 ?_5.
    } UNION {
      ?_2 sxcxcx:r47 ?_6.
      ?_6 sxcxcx:r79 ?_7.
      ?_7 sxcxcx:r103 ?_8.
      ?_8 sxcxcx:r104 ?_5.
    } UNION {
      ?_2 sxcxcx:r47 ?_6.
      ?_6 sxcxcx:r80 ?_9.
      ?_9 sxcxcx:52 ?_7.
      ?_7 sxcxcx:r103 ?_8.
      ?_8 sxcxcx:r104 ?_5.
    } UNION {
      ?_2 sxcxcx:r47 ?_6.
      ?_6 sxcxcx:r80 ?_9.
      ?_9 sxcxcx:r53 ?_10.
      ?_10 sxcxcx:r60 ?_5.
    }

    ?_5 sxcxcx:r20 ?_11.

    {
      ?_11 sxcxcx:r97 ?_12.
      ?_12 ssx:r66 ?evdate
    } UNION {
      ?_11 sxcxcx:r22 ?_13.
      ?_13 sxcxcx:r4 ?_14.
      ?_14 ssx:r66 ?evdate
    } UNION {
      ?_11 sxcxcx:r22 ?_13.
      ?_13 sxcxcx:r4 ?_14.
      ?_14 ssx:r68 ?evdate
    }
  }
  GROUP BY ?macro ?melabel ?event ?evlabel
}
